### ISSUE TITLE
引数の名前渡しの説明がない

### ISSUE THREAD

**Issue by hexx** [scalajp/scala_text#490]
https://docs.scala-lang.org/tour/by-name-parameters.html の機能。
「エラー処理」の章で説明なしに登場しているようなので、事前に説明が必要。

**Comment by xuwei-k** [comment]
とりあえず https://github.com/scalajp/scala_text/pull/497 で追加されてるのでclose
(もし、さらに修正や追記が必要なら再度openか、別issueで)
