### ISSUE TITLE
jsのライブラリの(セキュリティ)アップデート

### ISSUE THREAD

**Issue by xuwei-k** [scalajp/scala_text#510]
2019年9月現在以下の状態

https://github.com/scalajp/scala_text/network/alerts

![スクリーンショット 2019-09-27 14 30 24](https://user-images.githubusercontent.com/389787/65744474-67a59f80-e133-11e9-9e08-d7fbce8fba42.png)

**Comment by kmizu** [comment]
この辺、土日でちょっとアップデート試みてみます。

**Comment by kmizu** [comment]
ちょっとnpm周りでてこずってるので、明日（ってか今日）、調査引き続き試みます…。

**Comment by kmizu** [comment]
@xuwei-k 試してみたところ、脆弱性の大半がgitbook-cli が依存しているライブラリによるもののようで、しかも、gitbook-cliはそもそもアクティブに開発が続いていない、という事情があることがわかりました。 

- https://github.com/GitbookIO/gitbook-cli  (2年前から更新されてない）
- https://github.com/GitbookIO/gitbook

> As the efforts of the GitBook team are focused on the GitBook.com platform,
>  the CLI is no longer under active development.

なので、長期的には GitBook.com に移行するかそもそもGitBook捨てるといったあたり検討する必要がありそうです

**Comment by xuwei-k** [comment]
おっ…なるほど厳しいですね 😢

**Comment by kmizu** [comment]
これ、gitbook使ってる限りどうしようもない話ってことが判明したので、いったん閉じますね（とはいえ、脆弱性の警告が出てるの微妙ですが）。
