### ISSUE TITLE
Scalaテキスト移管/譲渡のお知らせをブログに書く

### ISSUE THREAD

**Issue by kmizu** [scalajp/scala_text#512]
これは主に私のタスクですが、

- https://blog.scalamatsuri.org/

にその辺の経緯と、今後のScalaテキストのメンテナンスに関して記事を書く予定です。とりあえず、ドワンゴ側とJSA側の方で記事はレビューしてもらってから、今週中に出せればって感じです。

**Comment by xuwei-k** [comment]
Scala祭のblogに書くの、何か変なちょっと気がする・・・？ 🤔 

とはいえ他のどこに書くかというと、微妙に難しいというか、ひとまず思いつくの以下くらいだが
- kmizuさんの個人blog？
- scalajpの適当なgithub page?(blogじゃないから書きづらそうだが)
- その他？

適当にscalajpというかJSAの人にmentionsして意見募るか @taisukeoe @gakuzzzz 
(既に話合ってたらすいません)

**Comment by xuwei-k** [comment]
大体察しついてるかもしれないが、 `Scala祭のblogに書くの、何か変` と思った理由を書いておくと、

ScalaMatsuriを運営している主体は現状あくまでJSAだが、JSAは(たしかにScalaMatsuriが理由で創設、存在、しているのも大きいだろうけど)、原理的にはScalaMatsuriとは直接関係ないそれ以外の活動も行うはずで、
このscala_textに関しては、そういうScalaMatsuri以外の活動であり、

JSA = ScalaMatsuri

ではないはずなので、違和感がある、という。

とはいえ、
「なんか適切なところが他になくて、ScalaMatsuriのblogに書くことに(逆に？)何かメリットがあって、考えた結果、あえてその方法を選択する」
というのなら、絶対に反対、というわけでもないですが

**Comment by xuwei-k** [comment]
https://blog.scalamatsuri.org/entry/2019/10/01/163533 あっ、なぜかもうscala matsuri blogで公開されてた・・・

**Comment by kmizu** [comment]
@xuwei-k あ、コメントみてなかったです。ちょっと申し訳ない…。その辺に関しては、個人ブログにいったん書こうかとも思ったところ、そもそも私個人の私物ではないので変だよなあということで、 @taisukeoe さんと話し合った結果、そこにのっけることになりました（一応、ScalaMatsuri以外のことも書いてるので）。

**Comment by kmizu** [comment]
@xuwei-k さんが色々貢献してくれてるのは大変助かるものの、このテキストへのコミットメントを求める立場にしちゃうとまずいかなと思って、個別に相談しなくて申し訳ないです（私は時間割けるものの、 @xuwei-k さんが十分時間割けるかわからないなあ、というあたりで）。

**Comment by taisukeoe** [comment]
今気づきました。

> 「なんか適切なところが他になくて、ScalaMatsuriのblogに書くことに(逆に？)何かメリットがあって、考えた結果、あえてその方法を選択する」

明確なメリットってほどじゃないですけど、scala_textはちょこちょこScalaMatsuriコンテンツの中でも参照してるから関連ないわけじゃないし、今後コントリビュータを広く募りたいならkmizuさんの個人ブログよりは適切かなぁ、ぐらいの理由でした。

**Comment by xuwei-k** [comment]
なるほど

**Comment by taisukeoe** [comment]
> この辺、 @xuwei-k さんが色々貢献してくれてるのは大変助かるものの、このテキストへのコミットメントを求める立場にしちゃうとまずいかなと思って、個別に相談しなくて申し訳ないです（私は時間割けるものの、 @xuwei-k さんが十分時間割けるかわからないなあ、というあたりで）。

補足すると、(publicにすると先方に迷惑がかかりそうな）譲渡契約周りの実務の相談をしていたinternalのチャンネル上でぽろっとこの話題が出たので、そのまま同じチャネルで話しちゃいました、みたいな経緯でした。
僕も気づかず申し訳ないです。

普通に考えると、原則scala_text関係の相談はこのrepositoryのissue上でやるのがいいと思います。
今後はそうしていきましょうー＞ @kmizu

**Comment by xuwei-k** [comment]
🙆‍♂ 

関連して(?)というか、あまり関連してないけど、思い出したのでここに書いておくけど、

scala_textはJSA(Japan Scala Association)に移管はするけど、別途github上では専用orgを新たに作ったほうがいろいろな都合上いい気もしたけど、まぁ若干今更感ある(?)

**Comment by kmizu** [comment]
> > この辺、 @xuwei-k さんが色々貢献してくれてるのは大変助かるものの、このテキストへのコミットメントを求める立場にしちゃうとまずいかなと思って、個別に相談しなくて申し訳ないです（私は時間割けるものの、 @xuwei-k さんが十分時間割けるかわからないなあ、というあたりで）。
> 
> 補足すると、(publicにすると先方に迷惑がかかりそうな）譲渡契約周りの実務の相談をしていたinternalのチャンネル上でぽろっとこの話題が出たので、そのまま同じチャネルで話しちゃいました、みたいな経緯でした。
> 僕も気づかず申し訳ないです。
> 
> 普通に考えると、原則scala_text関係の相談はこのrepositoryのissue上でやるのがいいと思います。
> 今後はそうしていきましょうー＞ @kmizu

承知です。

**Comment by taisukeoe** [comment]
> scala_textはJSA(Japan Scala Association)に移管はするけど、別途github上では専用orgを新たに作ったほうがいろいろな都合上いい気もしたけど、まぁ若干今更感ある(?)

確かにそれはそうですね 🤔 
scala_textのメンテナにしたら、ScalaMatsuriのinternalな情報が見えるのって権限の割り方としておかしい気がしますし。

今からでも移して良いんじゃないでしょうか。

**Comment by xuwei-k** [comment]
いやちゃんと個別に権限つければ、scala matsuriの情報見えることはそんなに無いとは思うけど、CIの並列数も分けておいた方が得、とかもある

**Comment by taisukeoe** [comment]
まあ確かにそうですね。
でも一緒に管理するより、分けといた方が権限管理の煩雑さは緩和されそう。

あとは料金プラン的には、

**Comment by xuwei-k** [comment]
ほー、じゃあ本当に移行するなら、別issue立てるか(?)

**Comment by taisukeoe** [comment]
別issue作るか、とも思ったけど、closedのまま議論するのも微妙なので一旦open。

**Comment by taisukeoe** [comment]
別issue作ったら閉じましょう

**Comment by kmizu** [comment]
とりあえず、私も分ける方向にした方が権限管理楽になっていい気はしますね。scala_text, scala_text_pdf とかが一つのorgにまとまった方が自然とも思いますし（ただ、そのための作業が多少めんどう？くらいでしょうか）

**Comment by xuwei-k** [comment]
続きはこっちで https://github.com/scalajp/scala_text/issues/520
